// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

DTTable Computation(const DTTable &green,const DTTable &red,
                    double step); // Step size for the mesh

#endif /* IT_computation_h */ 
